### ISSUE TITLE
tobs charts missing from charts.timescale.com

### ISSUE THREAD

**Issue by alzabo** [timescale/tobs#101]
While attempting to run tobs install, I receive the error message:

```
Error: could not install The Observability Stack: exit status 1 
Output: Error: failed to download "timescale/tobs" (hint: running `helm repo update` may help)
```

Digging around a bit more, it seems like the tobs and promscale charts are missing from charts.timescale.com.

The only 2 charts currently in the index.yaml file are the ones for timescaledb:

```
~> helm  search repo timescale
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                      
timescale/timescaledb-multinode 0.8.0                           TimescaleDB Multinode Deployment.
timescale/timescaledb-single    0.8.1                           TimescaleDB HA Deployment. 

~> curl https://charts.timescale.com/index.yaml  2>/dev/null | yq eval '.entries.[] | path | .[-1]' -
timescaledb-multinode
timescaledb-single
```

Looks like maybe the index file was clobbered when an update was made earlier today (based on timestamps in index.yaml)

**Comment by VineethReddy02** [comment]
Hi @alzabo 

Thanks for pointing this out. We had some issues with our helm charts yesterday. It is has been resolved now. Let us know if you are still facing any issues with the helm charts.  Closing the issue for now. :)
