### ISSUE TITLE
metrics whitelisting and scrape durations as chart parameters

### ISSUE THREAD

**Issue by sokoow** [timescale/tobs#105]
All,

I've noticed that tobs is indeed a pretty cool complete gizmo now, but there's a bigger problem when using it full time.

So, by default exporters and prometheus scrape all the metrics, invoking disk writes south of 40 megs/s - pretty big strain.I assume that if you runestablished server bases, with grafana dashboards created already for your needs, then you probably can easily list a subset of metrics you're only interested in. 

As a measure of decreasing mad scraping durations x number of default metrics gathered, I'd suggest an approach to parametrize both of these in the install process. What you think ?

**Comment by VineethReddy02** [comment]
Hi @sokoow 
We currently use [Prometheus helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus) to deploy Prometheus. If the upstream Prometheus supports metrics whitelisting we support it by default. It definitely sounds like an interesting use case. You can tune Prometheus configuration during the tobs install process even today.
