### ISSUE TITLE
Switch to or vendor kube-prometheus

### ISSUE THREAD

**Issue by gouthamve** [timescale/tobs#108]
We already have a project with a lot of the same goals in https://github.com/prometheus-operator/kube-prometheus. It has an amazing set of alerts, dashboards and recording rules and comes with Alertmanager too. The community is also behind that project.

Having said that, I like the UX of tobs. I think it will be better to wrap tobs on top of kube-prometheus rather than using helm charts like you do now. I know its a big change but it will literally make the project much much better. Hear me out:

1. Ship Prometheus Operator instead of Prometheus as adding relabelling rules is not trivial and operator makes it much easier. The example here: https://github.com/timescale/tobs/blob/c161c7f4451aabd0908fca6a370fcf3814b10458/chart/values.yaml#L98-L103 is wrong because you shouldn't scrape the service endpoint but rather individual pods.
2. Ship the dashboards, alerts and recording rules from kube-prometheus. They are maintained by the experts with a lot of collaboration from the community.
3. Also add alertmanager to the stack and make it easier to configure.

At this point it looks like kube-prometheus :) Why not just use it?

**Comment by gouthamve** [comment]
Just in case the issue sounds like I'm against tobs: 

I love it! I completely agree that we need better tooling and the jsonnet tooling around kube-prometheus is not for beginner users! I'm really glad there is work going into building better tooling, and just want to make sure there is collaboration and re-use where possible :)

**Comment by lilic** [comment]
Thanks, Goutham for opening the issue! I agree, our UX is not the best, it was primarily used by us who knew and later adopted by the community. With that said I do not think we are against improving kube-prometheus at all, we are super happy with new contributions and have it in a separate org with a governance model and maintainers and contributions from different companies. So looking forward to any issues how we can work together. 🎉 

For context, I am the maintainer of prometheus-operator and kube-prometheus :)

**Comment by bwplotka** [comment]
+100 to this. There is lot of effort made by the community already which is worth reusing. User-friendly API is what kube-prometheus is missing, but there are some ideas coming up, and something like this tool would be definitely some nice improvement!

**Comment by cevian** [comment]
Thanks everyone for the comment. There is a lot to think about here and to digest.

I think all three points made by @gouthamve make a ton of sense. (1) was already on our roadmap and (2) makes a ton of sense to do. 

I am wondering if we could do an even tighter integration as suggested here but see a few issues/questions:

1) I wonder if people care about packaging in helm. Originally we thought having the ability to deploy this as a subchart in Helm would be useful for people. From my (very rudimentary; please correct me if I am wrong) understanding of kube-prometheus it does not have a helm chart. We could try creating a Helm chart for kube-prometheus but I am not sure how it would interact with the jasonnet stuff and how subcomponents would be controlled.
2) jasonnet seems pretty complex. I image new users may get intimidated. Is it possible to create a yaml interface on top of the jasonnet stuff? Is it worth thinking about some kind of transpiler?
3) How does this look once we add tracing/logging. Is kube-prometheus just one of the tools we use? With Helm its pretty straightforward to add components but what does this look like with a dependency on something like kube-prometheus.

Anyway would love to hear feedback from you folks. This kicked off some very interesting discussions on the team.

**Comment by paulfantom** [comment]
Hi, kube-prometheus maintainer here :)

Answering @cevian questions:
1. Yes, there is already a helm chart based on kube-prometheus. You can take a look at it in https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
2. We recently refactored kube-prometheus to have a much easier interface than it had in the past. Take a look at our "entrypoint" file in https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/main.libsonnet and how component versions are set from JSON in https://github.com/prometheus-operator/kube-prometheus/blob/main/jsonnet/kube-prometheus/main.libsonnet#L31. This is not using YAML right now as jsonnet cannot parse YAML yet, but there is [a WIP PR to allow such feature](https://github.com/google/jsonnet/pull/888) and as soon as this is done we are going to switch from JSON to YAML. On top of this, we had a long-standing issue to make user experience better and we started experimentation around this so collaboration in this space would be much appreciated.
3. That depends on how you structure the project. From the side of kube-prometheus we try to focus on metrics primarily but at the same time be extensible (take a look at our example for enabling loki for logs - https://github.com/prometheus-operator/kube-prometheus/issues/555#issuecomment-635938188)

We are happy to jump on a call if you want, or help you further with any questions, thanks for being open to collaboration!

**Comment by cevian** [comment]
Hi again,

Sorry for the long delay in responding. We've done a bit of thinking and are gonna planning to add experimental support for Kube-Prometheus in #112 and plan to do more. In addition, I really like the idea of collaborating more and think @paulfantom 's idea of having a call is great.

So, I started a doodle poll to help schedule https://doodle.com/poll/6t9f9a9wu2pf53g6?utm_source=poll&utm_medium=link 
If next week isn't good for people, let me know and we can also do some other time.

Going to ping people in this thread who may be interested: @paulfantom @bwplotka @lilic @gouthamve @VineethReddy02 

Thanks and hope to talk soon.

**Comment by paulfantom** [comment]
Sorry @cevian, I was on vacation the last two weeks and just saw your doodle poll. Do you think we still can have this call?

**Comment by cevian** [comment]
@paulfantom I just saw this, sorry (ugh GitHub notifications). I just emailed you, hopefully will be easier to coordinate that way.

Thanks.

**Comment by cevian** [comment]
Hey all - an update. The 0.4.0 release switches to using the kube-prometheus helm chart as a sub-chart. So in large part this is implemented. We are still thinking about, and discussing with community members, how to make this integration even tighter so we could contribute parts of this upstream and get more involved with the community. 

But, I think that discussion is better done outside of this issue. Thus, closing this for now. I'd like to thank everyone who commented on this issue for suggestions on how to improve tobs. Please, don't hesitate to open more issues related to the ongoing task of better integration.
