### ISSUE TITLE
Could not install The Observability Stack 0.3.0

### ISSUE THREAD

**Issue by olegchorny** [timescale/tobs#121]
Hi, I'm little bit confused that no one else reported this issue, but I'm not able to install 0.3.0 due to "Error: could not install The Observability Stack: failed to parse helm show values from yaml to json yaml: mapping values are not allowed in this context"

I've tried `tobs install` atop of k8s 1.20 and 1.19 and got the same result. Can anyone confirm that it works on your side? Thanks.

**Comment by VineethReddy02** [comment]
Hi @olegchorny 
I just tried doing `tobs install` in the Digital ocean 1.20 k8s cluster and it worked as expected. tobs internally uses `helm` as a dependency and we expect it to be of version `3`. Can you confirm your helm version?

**Comment by olegchorny** [comment]
@VineethReddy02 thank you.

it seems like the issue was due to warning from helm about the insecure permissions to kubeconfig:
`WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: ~/test/kubeconfig`
probably, somehow, this message was included to the generated yaml file.

I've fixed the permission to file, and tobs install works like a charm. Thanks!
