### ISSUE TITLE
0.3.0 installer broken?

### ISSUE THREAD

**Issue by sokoow** [timescale/tobs#124]
All, I think 0.3 installer is broken:

```
# tobs install
Adding Timescale Helm Repository
"timescale" already exists with the same configuration, skipping
Fetching updates from repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "minio" chart repository
...Successfully got an update from the "timescale" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: could not install The Observability Stack: failed to parse helm show values from yaml to json yaml: mapping values are not allowed in this context
```

**Comment by VineethReddy02** [comment]
Hi!
`tobs` is working fine on my end & our CI runs the tests on tobs every day. Can you share the version of `helm`? Please make sure to use helm version >= 3.

**Comment by sokoow** [comment]
strange, i'm using helm 3:
```
helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

**Comment by sokoow** [comment]
ah who would have thought: it was wrong perms on kubeconfig

**Comment by lbogdan** [comment]
I think this is actually a bug in `tobs`:
https://github.com/timescale/tobs/blob/4b8e4731107f7f046dbab241d232bef514373aac/cli/pkg/utils/utils.go#L264-L266

You're using `out.CombinedOutput()`, which breaks when `helm` warns about Kubernetes  config file permissions on `stderr`, and that gets concatenated with the actual yaml.

**Comment by VineethReddy02** [comment]
Good catch! I will update this part to capture the expected output and to print the warnings...

**Comment by VineethReddy02** [comment]
Fixed in https://github.com/timescale/tobs/pull/132
