### ISSUE TITLE
Constraint violation months after the chart is up

### ISSUE THREAD

**Issue by adrianmiron** [timescale/tobs#125]
Hi,

I have the charts deployed on several clusters and i have an issue on one cluster where the promscale pod is not pushing data to the db because of this error : 

{"caller":"write.go:79","err":"ERROR: new row for relation \"aws_alb_target_connection_error_count_maximum\" violates check constraint \"aws_alb_target_connection_error_count_maximum_labels_check\" (SQLSTATE 23514)","level":"warn","msg":"Error sending samples to remote storage","num_samples":100,"ts":"2021-04-26T12:57:38.333Z"}

I have not changed anything in the setup in  a while  so it must be something new with the data. Can you please provide me a few commands for timescale to check the constraint , modify it, drop it or at least understand what it's details are ?

Thanks

**Comment by VineethReddy02** [comment]
@adrianmiron Do you still see this issue?

**Comment by adrianmiron** [comment]
I have worked around it by not saving that particular metric since i do not really use it .

**Comment by VineethReddy02** [comment]
Can you share the details on the Promscale version you encountered this issue in? And also how did you manage not to save that specific metric?

**Comment by ramonguiu** [comment]
Closing since we are not able to reproduce and have not received additional information.
