### ISSUE TITLE
0.4.1 might not be creating a secret properly

### ISSUE THREAD

**Issue by sokoow** [timescale/tobs#135]
I get this after trying to install from 0.4.1:

```
Events:
  Type     Reason     Age               From                                  Message
  ----     ------     ----              ----                                  -------
  Normal   Scheduled  <unknown>         default-scheduler                     Successfully assigned default/tobs-promscale-544d8c5f46-f8clm to XXX
  Normal   Pulled     9s (x5 over 51s)  kubelet, XXX Container image "timescale/promscale:0.1.4" already present on machine
  Warning  Failed     9s (x5 over 51s)  kubelet, XXX  Error: secret "tobs-timescaledb-passwords" not found
```

could someone confirm ?

**Comment by VineethReddy02** [comment]
Are you installing tobs using `tobs install` ? Can you share the output of `tobs version -d`

If you are installing directly using tobs helm-chart i.e. without tobs CLI. We expect you to create TimescaleDB secret in advance as described [here](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#creating-the-secrets) or you can also set `timescaledb-single.unsafe=true` in values.yaml. This will create the random TimescaleDB certs and passwords for you by which you can avoid creating secrets in advance (but this isn't recommended).  I will add the secrets creation reference to tobs docs, I just realized it's missing.

**Comment by FraBle** [comment]
I ran into the same issue. I recommend linking [the instructions](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#creating-the-secrets) for creating a secret in the [readme](https://github.com/timescale/tobs/blob/master/chart/README.md).

**Comment by VineethReddy02** [comment]
@FraBle Are you using tobs helm chart directly or tobs CLI to install the stack?

**Comment by FraBle** [comment]
Also, to provide more context: we're running it as sub-chart for a benchmarking suite. Our `Chart.yaml` contains:

```yaml
...
dependencies:
  ...
  - name: tobs
    version: 0.4.1
    repository: https://charts.timescale.com
    condition: tobs.enabled
  ...
```

**Comment by jgerry2002** [comment]
If anyone finds this issue and the docs still are not updated. Look in the timescaledb-single chart for a script named generate_kustomization.sh and modify accordingly. This will create the correct secret.

**Comment by VineethReddy02** [comment]
This is updated in the docs [here](https://github.com/timescale/tobs/tree/master/chart#creating-secrets)
