### ISSUE TITLE
There are a few links to `docs/cli-usage.md` in the tobs READMEs, but this file does not appear to exist in the repo.

### ISSUE THREAD

**Issue by jgpruitt** [timescale/tobs#146]
for example:
Our [**full usage docs**](docs/cli-usage.md) give a good overview of what you can do with the CLI tool.

**Comment by VineethReddy02** [comment]
Thanks for pointing this out. I dropped this file and missed to remove the reference from README.md. I will update the doc. :)

**Comment by andrewspiers** [comment]
Where should you look for this information now?

**Comment by VineethReddy02** [comment]
Here is the cli-usgae guide https://github.com/timescale/tobs/tree/master/cli#usage-guide

**Comment by VineethReddy02** [comment]
Fixed in #173
