### ISSUE TITLE
Grafana timescale datasource permissions

### ISSUE THREAD

**Issue by tomasfreund** [timescale/tobs#150]
Hi,

I have installed the stack successfully into my cluster and have a problem with the TimescaleDB.
My expectation was that the TimescaleDB data source in grafana would enable querying the data ingested by Promscale, instead it looks like TimescaleDB data source only offers tables from the grafana database in the query builder.

Is this the intended behavior? I expected the data source to have read access to the Prometheus data and not the grafana database.

**Comment by VineethReddy02** [comment]
Hi @tomasfreund 

There is no Grafana database in tobs. We created credentials for Grafana in TimescaleDB. And in the data source configuration, you see the Grafana read credentials. You can definitely query in Grafana using SQL queries. 

By default, you will find two datasources configured i.e.

1. Prometheus (This points to the Promscale endpoint you can query PROMQL queries) 
2. TimescaleDB (This points to the TimescaleDB you can use SQL queries)

I need to find these queries. I will update the SQL queries for graphing shortly...

**Comment by tomasfreund** [comment]
Hi, the issue is that the TimescaleDB data source only has permissions to access the grafana tables and not the Promscale tables.

**Comment by tomasfreund** [comment]
It seems that the issue was fixed in 0.6.0 - probably by this commit https://github.com/timescale/tobs/commit/614a42930dd87bb8de21b56783089b1f3f24dc99
