### ISSUE TITLE
Storage rotation/limiting

### ISSUE THREAD

**Issue by sokoow** [timescale/tobs#157]
Is there any gauge in configs to make storage limits/rotation working ? I think I've seen a 150gig setting somewhere in chart values, but it just doesn't work (it crosses 150 gig and tips my cluster over). Let us know and thanks in advance.

**Comment by VineethReddy02** [comment]
@sokoow can you be more elaborative on the issue? Do you mean the storage is exceeding `150Gi` even after providing the default storage limits? 

I didn't understand the context on gauge in config and limits/rotations. :/

**Comment by sokoow** [comment]
Yes sure, there it goes:

Let's say I am setting up 150Gi of my storage limit - cluster runs and runs till it reaches that, and then I need to extend my pvc to make it run further.

What I want, is some smart mixture of storage limit, when it starts to delete older metrics when PV is reaching say 95% of capacity. Another way of tackling this would be to have a metric cut out period (let's say max metrics age of 14 days, configurable), after which tobs would be deleting old metrics. Let me know if anything like that is already available.

**Comment by VineethReddy02** [comment]
Currently, we have default retention policy as `90 days ` you can change this based on your requiremnt (indirectly helps on tuning storage accordingly).

I am thinking out loud here. Tobs maybe not be right tool do storage rotation/limitng as you suggested. As tobs is a CLI and has no control over runtime until unless tobs cmds are triggered.

**Comment by VineethReddy02** [comment]
@sokoow do retention policies help you to do storage rotation? Can I close this issue?

**Comment by sokoow** [comment]
tomorrow is 8th day that I have 0.6 installed, we'll see

**Comment by sokoow** [comment]
so what does exactly ```
$ tobs metrics retention set * 7```

it says 
```Setting retention period for values.yaml to 7 days``` for installed tobs instance, so does it set it up in tobs database? How does it work ?

**Comment by VineethReddy02** [comment]
`tobs metrics retention set <metric-name> <days>` will let you to apply retention policy per metric basis. 

By default, the retention is set to `90 days`

You can change the default retention policy across all metrics by running the below cmd
```
$ tobs metrics retention set-default 30
Setting default retention period to 30 days
```

**Comment by sokoow** [comment]
ah, that will do - thanks ! :D
