### ISSUE TITLE
Custom postgres settings needed

### ISSUE THREAD

**Issue by sokoow** [timescale/tobs#158]
Is there any way to inject custom postgres.conf values? I'm struggling with setting up correct WAL behaviour and maximum worker count - default tobs install causes a lot of ioload later in the day, when it starts writing to disks in a manic way.

**Comment by VineethReddy02** [comment]
All the TimescaleDB related config can be configured using this [values.yaml ](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/values.yaml)from timescaledb-single helm chart

At tobs side, to customize TimescaleDB config, all you have to do is add the required config under `timescaledb-single` field:
```
timescaledb-single:
  ...
```

**Comment by VineethReddy02** [comment]
@sokoow Did you get a chance to configure postgres settings in TimescaleDB section of `values.yaml` as mentioned above?

**Comment by sokoow** [comment]
I should be good thanks
