### ISSUE TITLE
promscale is missing nodeSelector

### ISSUE THREAD

**Issue by FraBle** [timescale/tobs#160]
promscale gets currently scheduled on any available node since it's missing `nodeSelector`.
We're using node pools and it would be great to ensure promscale stays in our o11y node pool.

**Comment by VineethReddy02** [comment]
@FraBle nodeSelector is available in Promscale helm chart here is the Promscale [values.yaml](https://github.com/timescale/promscale/blob/master/helm-chart/values.yaml#L122)

All you have to do to add `nodeSelector` to Promscale is add below field to your tobs `values.yaml`
```
promscale:
  nodeSelector:
    ...
```

**Comment by VineethReddy02** [comment]
@FraBle are you able to configure nodeSelector as suggested above?

**Comment by FraBle** [comment]
Apologies for the late reply. 🙌  Looks like we got a typo in our long values file. It's working after fixing the typo.
