### ISSUE TITLE
Add an option to configure SQL queries to execute on TimescaleDB as pre/post upgrade hooks in tobs helm chart upgrade process without use of CLI

### ISSUE THREAD

**Issue by tomasfreund** [timescale/tobs#163]
There should be a way to install the helm chart without having to create the secrets manually.

Helm supports pre-install and pre-upgrade hooks. Perhaps a nice way to implement this would be to run a job with tobs CLI container and give it a script to execute.

If this is implemented, it would also be possible to implement a post-install and post-upgrade hook in a similar manner, allowing the user to execute an arbitrary script - e.g. configure retention, create extra users, etc.

Both of these changes would greatly reduce the complexity of installing the stack, CD tools like ArgoCD can't use a custom CLI tool without extensive configuration and people usually don't want to install another CLI tool in their CI pipeline.

All in all, the CLI tool is useful but I think it should be the other way around - enable us to use the tool from the helm chart (as hooks), don't require us to download it and use it.

**Comment by VineethReddy02** [comment]
Hi @tomasfreund 

You can definitely install tobs helm chart without CLI. The secrets the tobs CLI creates are TimescaleDB secrets. The TimescaleDB helm chart internally already uses the pre-install hook to create secrets. All you have to do to let TimescaleDB helm chart to creates in own secrets is 

Add this config to your `values.yaml`

```
timescaledb-single:
  unsafe: true
```

This generates a random password and certificate whereas if you use tobs CLI it creates a strong random password for database and self-signed certificate. 

If you do not want to use tobs CLI, you can substitute secrets creation with [this script](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/admin-guide.md#creating-the-secrets) mentioned in installation docs to create strong random password + self-signed certificate equivalent to tobs CLI.

**Comment by VineethReddy02** [comment]
Hi @tomasfreund 

Are you able to install tobs helm chart without CLI?

Can I close this issue?

**Comment by tomasfreund** [comment]
Hi, I was able to install it, I'm just a little bit concerned that the CA generated that way has a 5 year expiration. It seems long enough but who knows, it might cause some issues then.

Another thing is that there should be a way to execute some commands with the tobs cli as a post-upgrade hook - e.g. set retention or execute arbitrary commands against the database. Do you think that could be added?

**Comment by VineethReddy02** [comment]
Firstly apologies for the delayed reply. I was on vacation. 
I will give a thought about CA expiration. And will update you on that. 

Currently using tobs CLI you can set retention, chunk-interval with tobs CLi commands, You can also `exec` into DB container for performing desired operations on DB. Did you try using these options? Can you explain the use case where the post-upgrade hook could be useful in contrast to tobs CLI commands? Would love here your usecase. :)

**Comment by tomasfreund** [comment]
Hi, my use case would be to use the tobs CLi in a GitOps scenario - from a pipeline during helm upgrade or from a tool like ArgoCD. I don't want to install tobs on all machines running our CI and I don't want to exec into the container because that is a manual task and we try to automate everything we can in a way that is idempotent.

**Comment by VineethReddy02** [comment]
I am adding this as a feature request to our backlog. So you want an option to provide SQL queries to perform on TimescaleDB pre/post upgrade hooks on tobs upgrade.

**Comment by paulfantom** [comment]
This is done with https://github.com/timescale/tobs/pull/305 and will be available in next release.

If you feel like this issue is not complete, please reopen.
