### ISSUE TITLE
cli command helm show-values fails 

### ISSUE THREAD

**Issue by dnck** [timescale/tobs#168]
The following steps produce an error:

```
git clone https://github.com/timescale/tobs.git
cd tobs/cli 
go build .
./cli helm show-values 
>> Error: failed to get helm values: failed to download "timescale/tobs" (hint: running `helm repo update` may help)
```

I'm scratching my head. This seems like the most minimal first-example any sane person might run, and it does not work.

Of course, I can use helm directly, but since the cli tool is here, I would not mind using it if it worked...

**Comment by dnck** [comment]
I forgot to mention, one can make the cli work via, 

```
./cli helm show-values --chart-reference ../chart
```

**Comment by VineethReddy02** [comment]
@dnck I'm currently updating the docs on how to use `tobs` CLI. `tobs helm show-values` prints the default helm values if the chart is available locally, if not you can pass the path to helm chart as you mentioned above. Either ways `show-values` cmd should work. 
Can I close this issue as you figured it out?

**Comment by dnck** [comment]
Yes sir! Thank you, I will close it.
