### ISSUE TITLE
cli/tests/e2e-tests.sh is not posix sh compliant and breaks

### ISSUE THREAD

**Issue by dnck** [timescale/tobs#171]
Running the cli/tests/e2e-tests.sh produces an error in bash:

```
Creating cluster "tobs" ...
 ✓ Ensuring node image (kindest/node:v1.21.1) 🖼
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-tobs"
You can now use your cluster with:

kubectl cluster-info --context kind-tobs

Thanks for using kind! 😊
trap: SIGHUP: bad trap

```

I believe this is due to the following:

> In POSIX sh, prefixing signal names with 'SIG' is undefined.

https://github.com/koalaman/shellcheck/wiki/SC3048

**Comment by ramonguiu** [comment]
Thanks for reporting! We'll take a look.

**Comment by paulfantom** [comment]
That file was removed and we are no longer running those tests using a shell script, as such I consider this to be fixed. If you feel otherwise, please reopen.
