### ISSUE TITLE
Helm fails when using external timescaledb

### ISSUE THREAD

**Issue by stanislav-pidhaietskyi-by** [timescale/tobs#188]
When I try to install tobs and use external timescaledb, helm fails on rendering NOTES.txt file, timescaledb.fullname not defined
How to reproduce:
Run the helm install with disabled timescaledb chart
```
helm template promscale timescale/tobs --set timescaledb-single.enabled=false
```

Error:
```
Error: template: tobs/templates/NOTES.txt:128:94: executing "tobs/templates/NOTES.txt" at <{{template "timescaledb.fullname" $tsEnv}}>: template "timescaledb.fullname" not defined
```

**Comment by VineethReddy02** [comment]
Fixed in #187 

Should be out in out upcoming release...
