### ISSUE TITLE
Tobs timescaledb multinode support

### ISSUE THREAD

**Issue by koureasstavros** [timescale/tobs#190]
Is it possible to install tobs using timescaledb multinode using the Chart into Kubernetes Cluster?
I see that inside the charts is only timescaledb-single is present.

**Comment by VineethReddy02** [comment]
Currently, tobs only supports deploying TimescaleDB single-node setup. Multi-node support is on our project backlog.

**Comment by koureasstavros** [comment]
Thank you VineethReddy02 for the detailed answer, is there any official page with the backlogs?

**Comment by VineethReddy02** [comment]
We track backlog using Github issues. So this issue will be a placeholder to track the feature request :)

**Comment by paulfantom** [comment]
We decided internally that we won't be focusing on providing integration of multinode helm chart as a deployment option in tobs. If multinode is required, users still can:
1) Use our cloud offerings
2) Provision multinode setup via [timescaledb-multinode](https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-multinode)

In both those cases, users would need to disable timescaledb-single deployment in tobs (`timescaledb-single.enable: false`) and provide dburi (`promscale.connection.uri`) in helm values.
