### ISSUE TITLE
promscale with unified grafana alerting?

### ISSUE THREAD

**Issue by mdagit** [timescale/tobs#193]
I'm unclear on how much of Grafana's new "unified alerting" is dependent on cortex.
It would seem from:
   https://grafana.com/docs/grafana/latest/alerting/unified-alerting/
that it is impossible to have promql-style alerting rules (versus from dashboards) configured in the Grafana UI , unless the system is using the cortex storage backend?
Or is that somehow still supported when using promscale storage?

**Comment by paulfantom** [comment]
Right now, grafana "unified alerting" feature is available only with cortex.

**Comment by mdagit** [comment]
@paulfantom but what does that mean in practice?
Might a deployment have both cortex and promscale setup for storage, with cortex short-term only, but all alarms configured using it, while promscale is for longer-term analytics (but not alarm management)?
If so, is it documented somewhere how that dual storage is set up?
Thanks.

**Comment by paulfantom** [comment]
> Might a deployment have both cortex and promscale setup for storage, with cortex short-term only, but all alarms configured using it, while promscale is for longer-term analytics (but not alarm management)?

Yes it is possible. Someone would need to configure prometheus with 2 remote_write endpoints, one for cortex and one for promscale. Retention periods would need to be configured separately depending on system.

> If so, is it documented somewhere how that dual storage is set up?

No, I don't think this is documented anywhere. Your best bet is to follow cortex/grafana documentation for setting up that part and using promscale documentation to setup another part. From what I see those two systems can be configured together and the only point where they meet is at prometheus remote_write configuration.
