### ISSUE TITLE
Error during Helm uninstall and (re) install

### ISSUE THREAD

**Issue by werebear73** [timescale/tobs#196]
I was uninstalling using Helm and reinstalling and got the following error.  I am using the timescale/tobs (version 0.7.0)

Error: rendered manifests contain a resource that already exists. Unable to continue with install: Service "tobs-config" in namespace "default" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "tobs"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default" 

I manually deleted the Service "tobs-config" and it installed.  Not sure why helm left behind that service.

**Comment by VineethReddy02** [comment]
@werebear73 can you share the tobs CLI and deployed chart version?

**Comment by werebear73** [comment]
I'm not using the CLI but helm. Chart Version is 0.7.0

**Comment by paulfantom** [comment]
Can you share the content of `tobs-config` Service?

**Comment by werebear73** [comment]
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: tobs
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-12-01T15:03:50Z"
  labels:
    app: tobs-timescaledb
    app.kubernetes.io/managed-by: Helm
    chart: timescaledb-single-0.8.2
    cluster-name: tobs
    component: patroni
    heritage: Helm
    release: tobs
  name: tobs-config
  namespace: default
  resourceVersion: "4408751"
  uid: de2c6b57-1b03-4948-b4da-d9752e51a110
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: patroni
    port: 8008
    protocol: TCP
    targetPort: 8008
  selector:
    app: tobs-timescaledb
    cluster-name: tobs
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

**Comment by werebear73** [comment]
Here is the describe:

Name:              tobs-config
Namespace:         default
Labels:            app=tobs-timescaledb
                   app.kubernetes.io/managed-by=Helm
                   chart=timescaledb-single-0.8.2
                   cluster-name=tobs
                   component=patroni
                   heritage=Helm
                   release=tobs
Annotations:       meta.helm.sh/release-name: tobs
                   meta.helm.sh/release-namespace: default
Selector:          app=tobs-timescaledb,cluster-name=tobs
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                None
IPs:               None
Port:              patroni  8008/TCP
TargetPort:        8008/TCP
Endpoints:         192.168.109.114:8008,192.168.117.221:8008
Session Affinity:  None
Events:            <none>

**Comment by paulfantom** [comment]
@werebear73 we did quite a lot of improvements to the project and to make helm a primary installation method. I couldn't reproduce this issue with latest tobs (`0.11.1`) release, is this still an issue for you?
