### ISSUE TITLE
Error installing tobs with tracing (cert manager version clash)

### ISSUE THREAD

**Issue by gjedlicska** [timescale/tobs#204]
With cert-manager deprecating their old api versions, pre v1, `cert-manager.io/v1alpha2` resurces are not being served.

Trying to install into a cluster, where cert-manager >= 1.6 is installed fails, because the currently used `otel-operator` version (0.2.0) uses the old api.

Newer versions of the `otel-operator` now work with the stable cert-manager api. Can the referenced `otel-operator` version be updated in the tobs helm chart?

**Comment by VineethReddy02** [comment]
This is currently in work, The next tobs release should be out in 2 days. The latest tobs will install/support cert-manager version: `v1.6.1`

**Comment by gjedlicska** [comment]
Thanks for the response. 🙂 Can we keep this open until then?

**Comment by gjedlicska** [comment]
Hey @VineethReddy02 thanks, for the help, with the new release, tobs installed smoothly.
