### ISSUE TITLE
Fix DB-URI intall option using helm-chart

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/tobs#238]
Support tobs helm-chart to install using db-uri:

Helm install for 0.8.0 release uses db-uri from Promscale secret. If the user prefers to configure connSecretName with db-uri as secret. We cannot pass the db-uri from the secret in grafana-db-job as postgres container doesn’t support DBURI env. Maybe we should pass it in psql argument.

**Comment by paulfantom** [comment]
To do this we would need to have advanced templating in `values.yaml`, which is not available in helm. As such this is not possible to do just with helm.

My recommendation would be to make our (tobs) opinion on how connection to database should be handled and prevent using `uri`. It can still be an option for promscale helm chart, but for ease of integration of components in tobs, I don't think it is a good idea to have it available here.
