### ISSUE TITLE
name for kube-prometheus-stack is always overridden

### ISSUE THREAD

**Issue by paulfantom** [timescale/tobs#247]
I consider this a bug which does not work well when installing via helm with `--generate-name` flag.

**Comment by nhudson** [comment]
This will be a breaking change on upgrade.  We will need to provide documentation on how to handle that action.

**Comment by nhudson** [comment]
This may or may not cause upgrade issues.  Right now when testing, if you  are "upgrading" a previous install, it will error out with this error:

```helm upgrade --wait --timeout 15m chart-1660587400 chart/ -f chart/values.yaml

Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "prometheusrulemutate.monitoring.coreos.com": failed to call webhook: Post "https://tobs-kube-prometheus-operator.default.svc:443/admission-prometheusrules/validate?timeout=10s": x509: certificate is valid for chart-1660587400-kube-prom-operator, chart-1660587400-kube-prom-operator.default.svc, not tobs-kube-prometheus-operator.default.svc
```

Running another `helm upgrade` after this failure will result in the upgrade succeeding.

I think the best idea here if we want to remove this is to document that it has been removed and if you're upgrading to add back the line:

```
fullnameOverride: "tobs-kube-prometheus"
```
