### ISSUE TITLE
type error in values.yaml "'timescaledb-single.enabled' for chart timescaledb-single returned non-bool value"

### ISSUE THREAD

**Issue by hukarere** [timescale/tobs#250]
Hello,

During "tobs install", I got the following error:
> 2022/02/14 00:02:37 Warning: Condition path 'timescaledb-single.enabled' for chart timescaledb-single returned non-bool value

Even though the error is non-fatal and installation succeeded, it prevents some functions from working, for example, `tobs timescaledb superuser get-password` returns the same error.

The problem is with the following lines of values.yaml:

```
timescaledb-single:
  # disable the chart if an existing TimescaleDB instance is used
  enabled: &dbEnabled "true"
```

The last line above must be bool instead of string:
```
  enabled: &dbEnabled true
```

When I fixed values.html and ran 'tobs install -f values.html', this error went away.

**Comment by paulfantom** [comment]
We just merged a fix for this in https://github.com/timescale/tobs/pull/249 and will be releasing new version soon.

**Comment by hukarere** [comment]
@paulfantom,
Thank you!

**Comment by werebear73** [comment]
I'm still seeing this warning

**Comment by paulfantom** [comment]
We are scheduled to release a new tobs version on May 12. With new release this warning is no longer present. 

I am closing this issue. If you still see this problem occurring when using tobs 0.11.0, please reopen.
