### ISSUE TITLE
Helm install fails: Deployment in version "v1" cannot be handled as a Deployment

### ISSUE THREAD

**Issue by cneumaier** [timescale/tobs#264]
Hi Everybody, 

i just tried to install the helm chart but ended up with the following error:

> Error: INSTALLATION FAILED: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal bool into Go struct field EnvVar.spec.template.spec.containers.env.value of type string

Any suggestions on how to solve this?
Thanks in advance!

Some information on the installation:
Kubernetes Version: v1.23.1
Helm Version: 3

**Comment by paulfantom** [comment]
You need to wrap any `true` or `false` into quotes when passing values to `env` object.

Example:
```yaml
# Incorrect
env:
- name: test
  value: true
# Correct
env:
- name: test
  value: "true"
```

---

There was an issue in promscale helm chart that prevented usage of `extraEnv` setting. But this is fixed in the last promscale release and tobs will be including this fix in an upcoming release.

**Comment by paulfantom** [comment]
I am closing this as an issue was answered and there is no more questions from the author. Feel free to reopen or contact us on slack if you need more information.
