### ISSUE TITLE
Default Jaeger datasource endpoint for Grafana is incorrect

### ISSUE THREAD

**Issue by ricksalsa** [timescale/tobs#292]
In that jaeger section of the chart's values file, the promscaleTracesQueryEndPoint value for jaeger is incorrect. It currently points to:

`promscaleTracesQueryEndPoint: "{{ .Release.Name }}-promscale-connector.{{ .Release.Namespace }}.svc.cluster.local:9202"`

but should be:

`promscaleTracesQueryEndPoint: "{{ .Release.Name }}-jaeger.{{ .Release.Namespace }}.svc.cluster.local:16686"`

The current value causes a `502 Bad Gateway` when Grafana connects to the Jaeger-UI service.

**Comment by paulfantom** [comment]
Closing as this is fixed in promscale and next tobs release won't come with jaeger query deployment (https://github.com/timescale/tobs/pull/322).

Thanks @ricksalsa for you report and sorry that it took so long to fix this issue.
