### ISSUE TITLE
Add homebrew method for installation

### ISSUE THREAD

**Issue by remyleone** [timescale/tobs#295]
Could you add an homebrew method of installation for tobs?

**Comment by paulfantom** [comment]
We are currently working on overhauling tobs CLI and do not have plans to offer homebrew as a method of distributing CLI. This stance might change later.

**Comment by paulfantom** [comment]
tobs 0.11.0 is the last release which ships the CLI. From now on we are moving towards pure helm installation and as such there won't be a need to ship it via homebrew.
