### ISSUE TITLE
Charts Support tolerations and nodeSelector

### ISSUE THREAD

**Issue by ZQiannnn** [timescale/tobs#299]

**Comment by paulfantom** [comment]
Could you explain which parts of charts you would like to have support for nodeSelector and tolerations?

**Comment by ZQiannnn** [comment]
jaeger-query

**Comment by paulfantom** [comment]
We decided that jaeger query is no longer needed considering promscale 0.11.0 will have an embedded jaeger query endpoint and grafana has a good tracing UI.

Jaeger deletion is done in https://github.com/timescale/tobs/pull/322
