### ISSUE TITLE
tobs grafana change-password ' /bin/sh: syntax error: unexpected "("

### ISSUE THREAD

**Issue by guettli** [timescale/tobs#311]
```
guettli@p15:~/.kube$ tobs grafana change-password 'ad876RZ(/$ZRZQ'

Updating secret...
Changing password...
/bin/sh: syntax error: unexpected "("
Updating secret...
Error: could not change Grafana password: command terminated with exit code 2
```

Why do you use shell scripts? Is there no alternative?

[No shell scripting](https://github.com/guettli/programming-guidelines#no-shell-scripting)

**Comment by paulfantom** [comment]
> Why do you use shell scripts?

I ask myself the same question... Good news is that we are underway for a major refactor of how things work in tobs and removal of bash scripts is one of tasks on todo list.

**Comment by paulfantom** [comment]
We are deprecating CLI and thus `tobs grafana change-password` won't be available anymore.
