### ISSUE TITLE
Add tests to check data ingestion in tobs

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/tobs#324]
As currently, tobs includes all the components i.e. Prometheus, Otel collector, and Promscale that are required to test the ingestion, and querying of data.

As part of this issue add nightly tests to make sure the recommended config with the latest Otel-collector, Prometheus and Promscale works as expected with data ingestion of metrics and traces.

**Comment by paulfantom** [comment]
Related to https://github.com/timescale/tobs/issues/288

**Comment by paulfantom** [comment]
We can use `up` application to test the data flow (cc @onprem)
