### ISSUE TITLE
Add tests for installing tobs with timescale Cloud integration

### ISSUE THREAD

**Issue by paulfantom** [timescale/tobs#331]
**What is missing?**

We are not testing TimescaleCloud integration in tests.

**Why do we need it?**

To catch potential issues with that integration.

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
Possible test sequence:
1) provision DB with helm chart
2) compose DBURI
3) use DBURI from previous points as an external database

**Comment by paulfantom** [comment]
Depends on https://github.com/timescale/tobs/issues/473

**Comment by nhudson** [comment]
I believe with the merge of #531 we can close this?  Unless you think there is something else we need to add.
