### ISSUE TITLE
Switch grafana to use SQLite instead of using timescaledb instance

### ISSUE THREAD

**Issue by paulfantom** [timescale/tobs#338]
**What is missing?**

We are shipping our own, custom database instance for grafana. This seems to be unnecessary and just adding resource requirements. Instead I would propose to revert to using native grafana sqlite implementation. Users should still be able to connect grafana to postgresql if they wish to.

**Why do we need it?**

Additional components increase security risk as well as potential tech-debt.

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
Relates to #371

**Comment by Davincible** [comment]
Could you elaborate a bit more on why you decided on this change? As I was a bit confused by it. 

> Additional components increase security risk as well as potential tech-debt.

If we are using a timescaledb instance anyways, for metrics and often also business services, why not use it for grafana as well? Extra components, security, and tech-debt seem like non-issues in that case, besides that it could potentially perform better.
