### ISSUE TITLE
tobs upgrade -y flag not working

### ISSUE THREAD

**Issue by Davincible** [timescale/tobs#382]
The `-y` flag works with `tobs install`, but not (fully) with `tobs upgrade`. 

If I run `tobs upgrade -y`, it first asks if I want to install, since it hasn't been installed, this prompt is bypassed with the `-y` flag, but the subsequent prompt for installing cert-manager is not bypassed.

**Comment by Davincible** [comment]
I presume this is the culprit:
https://github.com/timescale/tobs/blob/b8911db7b8adb3197a979c0043e85a12dc470f5f/cli/cmd/upgrade/upgrade.go#L123-L126
Here the option `confirmActions` is not set, since it's not exported it can't be directly set.

```
 s := install.InstallSpec{ 
 	ConfigFile: file, 
 	Ref:        ref, 
 } 
```

**Comment by paulfantom** [comment]
You are correct with your assessment, would you like to contribute your finding in a form of a PR?

**Comment by Davincible** [comment]
I could, but I wasn't sure if its okay to export the field (that would be the easiest solution)
