### ISSUE TITLE
Can't get Alertmanager URL using provided syntax

### ISSUE THREAD

**Issue by axfelix** [timescale/tobs#387]
**What happened?**

Ran `export POD_NAME=$(kubectl get pods --namespace default -l "app=alertmanager,alertmanager=tobs-kube-prometheus-alertmanager" -o jsonpath="{.items[0].metadata.name}")` as recommended to get Alertmanager URL

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**

* tobs installation method:

- [x] cli
- [ ] helm chart

* tobs version:

Tobs CLI Version: 0.7.0, latest tobs helm chart version: 0.10.1

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind:

DOKS

* tobs Logs:

```
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.name}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}
```

**Comment by ramonguiu** [comment]
@axfelix it looks like the kubectl command didn't return anything even though it should have.

I've tested and I see the same issue because the alertmanager deployed by tobs does not have the `app=alertmanager` label.

Could you try instead with
`export POD_NAME=$(kubectl get pods --namespace default -l "alertmanager=tobs-kube-prometheus-alertmanager" -o jsonpath="{.items[0].metadata.name}")` ?

**Comment by paulfantom** [comment]
This should be fixed in https://github.com/timescale/tobs/pull/388 and available in next tobs release.

If you want to port-forward, I would recommend port-forwarding to an SVC as alertmanager can run in a cluster mode. To do that you can use:
```
kubectl --namespace default port-forward service/tobs-kube-prometheus-alertmanager 9093:9093
```
