### ISSUE TITLE
Update docs to not reference tobs CLI and point to helm usage

### ISSUE THREAD

**Issue by paulfantom** [timescale/tobs#393]
**What is missing?**

As in title

**Why do we need it?**

We are deprecating tobs CLI

**Anything else we need to know?**:

**Comment by Rajakavitha1** [comment]
@paulfantom you might want to open an issue here as well https://github.com/timescale/docs/issues. So that https://docs.timescale.com/promscale/latest/installation/tobs/#configure-tobs-for-your-kubernetes-cluster is updated as well.
