### ISSUE TITLE
install questions

### ISSUE THREAD

**Issue by marsty339** [timescale/tobs#415]
when I run helm install --wait --timeout 10m tobs timescale/tobs
Error: no Secret with the name "tobs-certificate" found
```
helm list
NAME	NAMESPACE	REVISION	UPDATED                                	STATUS	CHART      	APP VERSION
tobs	default  	1       	2022-06-10 14:51:24.457333106 +0800 CST	failed	tobs-0.10.1	0.10.1
the helm release status is failed,when I deal with same pod not running, not something to continu..

NAME                                                        READY   STATUS      RESTARTS   AGE
alertmanager-tobs-kube-prometheus-alertmanager-0            2/2     Running     0          18m
opentelemetry-operator-controller-manager-7467bdc8b-rjg9p   2/2     Running     0          18m
prometheus-tobs-kube-prometheus-prometheus-0                2/2     Running     0          18m
tobs-connection-secret-mdwqp                                0/1     Completed   0          18m
tobs-grafana-6894864595-7844f                               3/3     Running     3          18m
tobs-grafana-db-j7rcc                                       0/1     Completed   2          18m
tobs-kube-prometheus-operator-5874b95798-55cl4              1/1     Running     0          18m
tobs-kube-state-metrics-56c568fdcc-8mdzq                    1/1     Running     0          18m
tobs-prometheus-node-exporter-fqc4j                         1/1     Running     0          18m
tobs-promlens-7f778cc958-vzdpw                              1/1     Running     0          18m
tobs-promscale-648d58d4f5-kgl52                             1/1     Running     3          18m
tobs-timescaledb-0                                          1/1     Running     0          18m
```
not opentelemetrycollectors  cr , how can i to do? 
when I delete helm release tobs, the pod tobs-opentelemetry-collector-5f5889956d-8nbb2 is creating....

**Comment by paulfantom** [comment]
We are looking into issue with `no Secret with the name "tobs-certificate" found` during installation.

As for:
> when I delete helm release tobs, the pod tobs-opentelemetry-collector-5f5889956d-8nbb2 is creating....

We are tracking this issue in https://github.com/timescale/tobs/issues/365

**Comment by paulfantom** [comment]
@marsty339 could you check if this is still the case when using tobs `0.11.1`?

**Comment by marsty339** [comment]
> @marsty339 could you check if this is still the case when using tobs `0.11.1`?

 helm install --wait --timeout=10m tobs timescale/tobs
Error: secrets "tobs-pgbackrest" already exists
# kubectl  get po
NAME                                                         READY   STATUS      RESTARTS      AGE
alertmanager-tobs-kube-prometheus-alertmanager-0             2/2     Running     0             45s
alertmanager-tobs-kube-prometheus-alertmanager-1             2/2     Running     0             44s
alertmanager-tobs-kube-prometheus-alertmanager-2             2/2     Running     0             43s
opentelemetry-operator-controller-manager-7c985ff6f9-l8mnr   2/2     Running     0             55s
prometheus-tobs-kube-prometheus-prometheus-0                 2/2     Running     0             45s
prometheus-tobs-kube-prometheus-prometheus-1                 2/2     Running     0             44s
tobs-connection-secret-b9k4b                                 0/1     Completed   0             55s
tobs-grafana-7cd8df4694-qg7kz                                3/3     Running     0             55s
tobs-kube-prometheus-operator-56c9986ff4-8wx6c               1/1     Running     0             55s
tobs-kube-state-metrics-677c9b4fd4-qvf7f                     1/1     Running     0             55s
tobs-prometheus-node-exporter-6wxgr                          1/1     Running     0             55s
tobs-promscale-f74b845d8-cdknf                               1/1     Running     2 (42s ago)   55s
tobs-timescaledb-0                                           1/1     Running     0             55s
The installation still has errors，And it feels very complicated to install.
tobs 0.11.1 Requires  k8s version 1.23+,but my cluster version is 1.21.4。。。

**Comment by marsty339** [comment]
@paulfantom 
helm install --wait --timeout 10m tobs timescale/tobs
Error: secrets "tobs-certificate" already exists
kubectl  get po
NAME                                                         READY   STATUS      RESTARTS       AGE
alertmanager-tobs-kube-prometheus-alertmanager-0             2/2     Running     0              2m17s
alertmanager-tobs-kube-prometheus-alertmanager-1             2/2     Running     0              2m17s
alertmanager-tobs-kube-prometheus-alertmanager-2             2/2     Running     0              2m17s
opentelemetry-operator-controller-manager-7c985ff6f9-2hnw2   2/2     Running     0              2m31s
prometheus-tobs-kube-prometheus-prometheus-0                 2/2     Running     0              2m16s
prometheus-tobs-kube-prometheus-prometheus-1                 2/2     Running     0              2m16s
tobs-connection-secret-ng466                                 0/1     Completed   0              2m31s
tobs-grafana-5dfc6fb499-4vkk5                                3/3     Running     0              2m31s
tobs-grafana-db-9vp8h                                        0/1     Completed   2              2m31s
tobs-kube-prometheus-operator-56c9986ff4-4rz5p               1/1     Running     0              2m31s
tobs-kube-state-metrics-677c9b4fd4-ljh9g                     1/1     Running     0              2m31s
tobs-prometheus-node-exporter-fnfh9                          1/1     Running     0              2m31s
tobs-promscale-f74b845d8-jwf4w                               1/1     Running     3 (113s ago)   2m31s
tobs-timescaledb-0                                           1/1     Running     0              2m31s
