### ISSUE TITLE
[Feature] - Grafana Promscale datasource dynamic credential provisioning

### ISSUE THREAD

**Issue by Davincible** [timescale/tobs#448]
Currently, Tobs only allows you to statically configure Timescaledb credentials for Grafana, both as backend and datasource. This forces you to either put passwords in a Git repo, or use a helm secret solution. Neither of which fit within my workflow. It would be nice if we could provide a pre-existing secret with credentials for Grafana to use as Promscale datasource.

**Comment by Davincible** [comment]
Actually the main reason besides wanting no creds in a git repo, is wanting the passwords to be randomly generated as they're only used by the Grafana service. Perhaps it could be a nice option to randomly generate the password if its set to `""`

**Comment by paulfantom** [comment]
Great idea! We already have something like that for handling timescaleDB password and injecting it into promscale.

**Comment by paulfantom** [comment]
Related to https://github.com/timescale/tobs/issues/489

Most likely this will be fixed with https://github.com/timescale/tobs/pull/490

**Comment by paulfantom** [comment]
I am closing this as #490 is merged. Please reopen if in your opinion tobs 0.13.0 (release pending) is still not delivering this feature.
