### ISSUE TITLE
Access to ServiceAccount token should be restricted

### ISSUE THREAD

**Issue by paulfantom** [timescale/tobs#461]
**What happened?**

Pods which are not contacting kubernetes API have SA token mounted which is a security threat. We should consider implementing [mechanisms from kube-prometheus project](https://github.com/prometheus-operator/kube-prometheus/issues/1589) and prevent mounting SA token in following objects:

```
    Deployment - test-grafana 
    Deployment - test-promscale 
    Pod - test-grafana-test 
    ServiceAccount - test-grafana 
    ServiceAccount - test-grafana-test 
    ServiceAccount - test-prometheus-node-exporter 
    ServiceAccount - test-promscale-initializer-sa 
```

**Comment by nhudson** [comment]
Fix for `Deployment - test-promscale` is here: https://github.com/timescale/promscale/pull/1559

**Comment by nhudson** [comment]
Fix for `ServiceAccount - test-promscaleinitializer-sa` is here: https://github.com/timescale/tobs/issues/461

The rest will need to be fixed upstream at some point

**Comment by nhudson** [comment]
> Fix for `ServiceAccount - test-promscaleinitializer-sa` is here: #461
> 
> The rest will need to be fixed upstream at some point

With this we ended up explicitly setting `automountServiceAccountToken` to be `true` since  it actually accesses the Kubernetes API.
