### ISSUE TITLE
TimescaleDB service name is <release-name>

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/tobs#469]
**What happened?**
1. The TimescaleDB service name is the same as `<release-name>`, Which makes it hard to find the database service.
2. The TimescaleDB service doesn't include any selector labels. The port-forward using service is failing, without selector labels, we cannot make use of a service object. 

**Did you expect to see something different?**
Change the service name to `<release-name>-timescaledb` or something similar which is easy to find.

**How to reproduce it (as minimally and precisely as possible)**:
Default installation

**Environment**

* tobs installation method:

- [ ] cli
- [X] helm chart

* tobs version:

  `0.11.3`

**Comment by nhudson** [comment]
@VineethReddy02 timescale/helm-charts#403 was merged.  I am going to close this, if you feel like it needs to be reopened, please do so.
