### ISSUE TITLE
grafana role doesn't get created in postgres

### ISSUE THREAD

**Issue by nhudson** [timescale/tobs#489]
The `grafana` role that gets created in `0.11.x` [here](https://github.com/timescale/tobs/blob/release-0.11/chart/templates/grafana-datasource-sql.yaml#L14-L30) no longer works with the `main` branch.

We will need to move this into the `custom-secret-scripts` `Secret` to be picked up by the [timescaledb-single](https://github.com/timescale/timescaledb-kubernetes/tree/master/charts/timescaledb-single) Helm chart.

**Comment by nhudson** [comment]
Looks like all that is wrong what the name of the `Secret` in the `timescaledb-grafana-datasource.yaml` template.  

It was named `custom-init-scripts` and according to the [timescaledb-single Helm chart](https://github.com/timescale/timescaledb-kubernetes/blob/master/charts/timescaledb-single/values.yaml#L277-L279) it should be `custom-secret-scripts`

**Comment by paulfantom** [comment]
That Secret is also storing password as an environment variable. Maybe we can mount the secret also in grafana pod and use it for datasource setup? It seems that grafana allows environment variable expansion in datasource provisioning as per https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables

We should change the name of the variable though so it is clear that the variable is about TS datasource. Maybe sth like "GRAFANA_TS_DS_PASSWORD` or alike?
