### ISSUE TITLE
Issue with install and uninstall using helm

### ISSUE THREAD

**Issue by umgbhalla** [timescale/tobs#534]
**What did you do?**
Unnstalled tobs using helm

**Environment**
EKS, with kubernetes 1.22

* tobs version: 0.10.1

  `tobs version`

    

    

* Kubernetes version information:  1.22

  `kubectl version`

    

* Kubernetes cluster kind: eks

![10-08-22-43](https://user-images.githubusercontent.com/67634565/183941634-e9c4865e-032a-4e90-bba8-a2ea702244fd.png)

Why on `helm delete tobs` are these deployment/services not deleted ? is this supposed to happen ?

**Comment by nhudson** [comment]
This is a known issue, described in #365.  It's due to some limitations with Helm that we currently do not have a fix for.  For now if you want to completely remove the installation, the best method is to delete the namespace you installed it to.

**Comment by umgbhalla** [comment]
after removing this completly , and doing a `tobs install` with cli this happens
![10-08-22-10](https://user-images.githubusercontent.com/67634565/183947853-087c7b1d-6c88-4a4f-8969-5bf4f89b4c15.png)
 
 with `helm upgrade --install tobs  timescale/tobs --version 0.10.1`
 ![10-08-22-14](https://user-images.githubusercontent.com/67634565/183949287-a2955a0c-58b0-4b06-8829-f0c62d57e670.png)

**Comment by nhudson** [comment]
@umgbhalla can you try it with the latest release of tobs? [v12.0.0](https://github.com/timescale/tobs/releases/tag/12.0.0)

The CLI is considered deprecated as well.  I would also suggest installing to a specific namespace for the tobs stack if you can.

**Comment by siva-kubikk** [comment]
@nhudson I ran into the same issue as well when trying to install with tobs. If the tobs cli is deprecated, what is the best way to install tobs that can be easily automated and added as part of a CI/CD pipeline?

```
$ tobs install -y --version '12.0.0'
cert-manager version v1.6.1 exists in the cluster, skipping the installation...
Error: could not install The Observability Stack: failed to find the value from the keys in values.yaml [promscale openTelemetry enabled]
```

**Comment by nhudson** [comment]
@siva-kubikk the CLI is deprecated with the latest version of tobs (via #471).  The only way to install it is with Helm right now.

**Comment by siva-kubikk** [comment]
@nhudson Got it.

**Comment by umgbhalla** [comment]
@nhudson , helm install in a new namespace defiantly worked , i was wondering if i can install `0.12.0` on eks (which is on k8s 1.22)

**Comment by nhudson** [comment]
@umgbhalla great to hear!  As for supporting Kubernetes 1.22.x, it hasn't been tested with that old over a version.  I would say for sure it will work with 1.23 & 1.24 for sure.  I would suspect that there will be some compatibility issues, but like I said it hasn't been tested.
