### ISSUE TITLE
Include Promscale recommended tsdb config by default

### ISSUE THREAD

**Issue by VineethReddy02** [timescale/tobs#538]
**What is missing?**

The database offered in Tobs is primarily/solely used by Promscale Connector. For better performance of Promscale, we recommend tuning some database configuration documented [here](https://docs.timescale.com/promscale/latest/recommendations/config-recomm/#database-configuration). 

**Why do we need it?**

This improves the performance of the database in Tobs without a requirement or overhead for users to modify this as per Promscale recommendation.

**Comment by paulfantom** [comment]
We are waiting for timescaledb-tune to support profiles and after that, we're going to include a said profile to be enabled by default.
