### ISSUE TITLE
Automated downsampling

### ISSUE THREAD

**Issue by braunsonm** [timescale/tobs#558]
**What is missing?**

A feature that I would love to use more is promscales downsampling. However it is pretty low level if you want to do continuous aggregates. It involves running SQL commands against your timescaledb manually.

It would be nice if this chart could handle some of this automatically, basically giving it your SQL queries, or metric names, and running these queries as a job for you automatically.

**Why do we need it?**

It would allow greater adoption of downsampling features that are offered in timescale

**Comment by Harkishen-Singh** [comment]
Note: We are working on the design of automatic metric-rollup (with option to choose multiple resolutions) natively in Promscale. This should be out (probably in beta) sometime next quarter based on the current plans.

**Comment by nhudson** [comment]
@braunsonm I am going to close this issue as it really should be in the [timescale/promscale](https://github.com/timescale/promscale) issue list.  If you feel like this is really a tobs related issue, please reopen.

**Comment by braunsonm** [comment]
@nhudson Wouldn't this be related to tobs as it configures promscale? I guess this could be seen on both if promscale doesn't have an easy way to configure this in the first place. Perhaps @Harkishen-Singh will address that.

**Comment by nhudson** [comment]
@braunsonm I will go ahead and reopen this to discuss with the team, but I think if we did add something that it would be done in the [promscale helm chart](https://github.com/timescale/helm-charts/tree/main/charts/promscale).  Either way I will reopen the issue.  Thanks!

**Comment by nhudson** [comment]
@braunsonm I have created a new feature request for the Promscale Helm Chart here: https://github.com/timescale/helm-charts/issues/427

For now I will close this issue in favor of the new one.  Thanks for the ask!
