### ISSUE TITLE
Flag to disable grafana secret

### ISSUE THREAD

**Issue by Davincible** [timescale/tobs#593]
Would be nice to get a flag to disable the generation of this secret all together. E.g. I want to use postgres as granfana backend, but also don't want to put passwords in the values.yaml. So I dynamically create a secret and provide all the required values using `grafana.envFromSecret`. In that case this secret is redundant

https://github.com/timescale/tobs/blob/main/chart/templates/grafana-db-sec.yaml

**Comment by nhudson** [comment]
@Davincible #600 should fix this.

**Comment by Davincible** [comment]
Sweet, thanks
