### ISSUE TITLE
Install fails due to "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints

### ISSUE THREAD

**Issue by theelderbeever** [timescale/tobs#638]
**What happened?**
Install fails due to underlying coreos chart configuration.

**Did you expect to see something different?**
Install should succeed.

**How to reproduce it (as minimally and precisely as possible)**:
```
helm install --wait tobs timescale/tobs -n tobs --version 17.12.2
```

**Environment**

* tobs version:
`Helm Chart 17.12.2`

* Kubernetes version information:

```
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.23.13-eks-fb459a0
```

* Kubernetes cluster kind:

AWS EKS

* tobs Logs:

```
❯ helm install --wait tobs timescale/tobs -n tobs
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ServiceMonitor.spec.endpoints[0]): unknown field "enableHttp2" in com.coreos.monitoring.v1.ServiceMonitor.spec.endpoints
```

**Anything else we need to know?**:

**Comment by paulfantom** [comment]
This field was added fairly recently in prometheus-operator and it should be available in tobs with version 20.0.0.

Please reopen if it still doesn't work with recent tobs versions.
