### ISSUE TITLE
shellcheck reports SC2086 in test-metrics.sh

### ISSUE THREAD

**Issue by nhudson** [timescale/tobs#672]
**What happened?**

[shellcheck](https://github.com/koalaman/shellcheck) was updated today and is now reporting that the `chart/scripts/test-metrics.sh` script failing on [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086).  

Looks like the update to the github action this morning is now showing this as a failure code.

```
Notice: ./chart/scripts/test-metrics.sh:50:6: note: Double quote to prevent globbing and word splitting. [SC2086]
Notice: ./chart/scripts/test-metrics.sh:53:6: note: Double quote to prevent globbing and word splitting. [SC2086]
Notice: ./chart/scripts/test-metrics.sh:56:6: note: Double quote to prevent globbing and word splitting. [SC2086]
```

**Did you expect to see something different?**

I would expect it to not fail

**How to reproduce it (as minimally and precisely as possible)**:

run shellcheck against the `chart/scripts/test-metrics.sh` script

**Comment by paulfantom** [comment]
Fixed in 20.0.0 release.
