### ISSUE TITLE
Adjust for moving of the upstream prom helm repo

### ISSUE THREAD

**Issue by cevian** [timescale/tobs#74]
The repo has moved to https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus

At least the Helm hub repo link in https://github.com/timescale/tobs/tree/master/chart#additional-configuration-for-prometheus needs to be adjusted. There may be other things as well

**Comment by blagojts** [comment]
Opened #75 but there are still some references to stable/* in the cli tests. Will modify those in a separate PR because I need to change the image versions used there
