### ISSUE TITLE
how to update prometheus configs

### ISSUE THREAD

**Issue by nevetS** [timescale/tobs#87]
What is the recommended way to update your prometheus configuration with tobs?

e.g.  I want to add scrape configs, alerting rules, etc.

**Comment by blagojts** [comment]
Hey, this is a duplicate of #72 check it out for our answers there, and this part of the README https://github.com/timescale/tobs#configuring-the-stack

Everything is configurable through the values.yaml file that the helm charts use

**Comment by nevetS** [comment]
Understood, and thank you.  

But... the documentation you pointed to spells out:

> To modify the settings, first create a values.yaml file:
> 
> tobs helm show-values > values.yaml
> 
> Then modify the values.yaml file using your favorite editor. Finally, deploy with the new settings using:
> 
> tobs install -f values.yaml
> 

and the result is:
```
tobs install -n tobs --namespace monitoring -f ./values.yaml
Adding Timescale Helm Repository
"timescale" has been added to your repositories
Fetching updates from repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "codecentric" chart repository
...Successfully got an update from the "timescale" chart repository
...Successfully got an update from the "bitnami" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈
Installing The Observability Stack
Error: could not install The Observability Stack: exit status 1
Output: Error: cannot re-use a name that is still in use
```

Additionally, the out-of-the-box stable prometheus chart that this leverages will load a configmap reloader, so that you can update the configmap and receive new values.

Unfortunately, the configmap contains four files, and I don't see a straightforward way of editing them.  I can output the files, but updating them is problematic without overwriting the helm tags.

---
At this point, I'm relegated to just using helm to upgrade tobs with additional values, and while that's fine for now, it doesn't scale well.  Scrape configs can get pretty big and adding them all under prometheus.extraScrapeConfigs and running a helm upgrade will upgrade the chart unless you specify `--version {fixed-version}`.  

I think the instructions in this regard really should be more specific, and the advice to run install again to update configuration should be changed, or the workflow that I experienced blocking that action should be revised.

**Comment by VineethReddy02** [comment]
Hi @nevetS 
We are working on `tobs upgrade` flow [here](https://github.com/timescale/tobs/pull/90). That should address the problem you faced. For now, we expect user to modify Prometheus config in `values.yaml`. But we do have plans to provide an easier way for to users in updating prometheus config. As that's the only component that needs updations frequently.

**Comment by nevetS** [comment]
Thank you!
