### ISSUE TITLE
grafana pod error

### ISSUE THREAD

**Issue by junhwani** [timescale/tobs#92]
after tobs install

Its error comes up this

```
root@master:~/tobs/chart# k logs -f tobs-grafana-74b75c676d-tmlv7
error: a container name must be specified for pod tobs-grafana-74b75c676d-tmlv7, choose one of: [grafana-sc-dashboard grafana] or one of the init containers: [grafana-sc-datasources]
```

how can i solve it?

**Comment by blagojts** [comment]
What you're seeing are the init containers that create the starting dashboards and starting data sources for grafana, so you already have the deployed Promscale and Prometheus as data sources, and some dashboards to monitor the cluster already when you log in to Grafana. The main grafana container will start after them. 

When you have a pod with multiple containers in grafana you need to specify the container name for `k logs`
The command would look like `k logs -f <pod-name> <container-name>`
