### ISSUE TITLE
"invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable" when using KUBECONFIG env variable

### ISSUE THREAD

**Issue by heyleke** [timescale/tobs#94]
Some parts of tobs do not respect KUBECONFIG env variable when using tobs install, leading to an error message 
```
invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

Seems the tobs helm parts are not suffering from this issue

**Comment by VineethReddy02** [comment]
As this is addressed in #97 closing this issue.
