### ISSUE TITLE
configuring the stack docs fail

### ISSUE THREAD

**Issue by SvenDowideit** [timescale/tobs#96]
did a `tobs install`, then

```
sven@x1carbon:~$ tobs helm show-values > values.yaml
sven@x1carbon:~$ tobs install -f values.yaml
Adding Timescale Helm Repository
"timescale" already exists with the same configuration, skipping
Fetching updates from repository
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "timescale" chart repository
Update Complete. ⎈Happy Helming!⎈
Installing The Observability Stack
Error: could not install The Observability Stack: exit status 1 
Output: 
Error: cannot re-use a name that is still in use
```

**Comment by SvenDowideit** [comment]
I'm using k3s, with the config file world readable - and that also shows that the internal exec is merging stderr and stdout - so the original values.yaml has 2 STDERR WARNINGS in it - which also creates a hidden YAML->JSON conversion error

**Comment by SvenDowideit** [comment]
does it "just" need a `tobs uninstall` first? or is there a better way?

**Comment by VineethReddy02** [comment]
Hi @SvenDowideit 

If my understanding is right, You are trying to upgrade the existing tobs installation by updating the `values.yaml` To support upgrades we are working on `tobs upgrade` feature [here](https://github.com/timescale/tobs/pull/90). That should allow the upgrades. 

In the mean time, you should be able to upgrade using `helm cmds` or `uninstalling & installing back` should work too.

**Comment by SvenDowideit** [comment]
aha - yes - I'm trying to update the tobs config using the info at https://github.com/timescale/tobs#configuring-the-stack 

sounds like `./bin/tobs upgrade -f ./../chart/values.yaml` will be an eventual replacement for that info - but atm, its misleading :)

**Comment by VineethReddy02** [comment]
We will update the docs accordingly. 
Thanks for pointing this out. :)

**Comment by ramonguiu** [comment]
@paulfantom  @VineethReddy02 is this still an issue or can this be closed?

**Comment by VineethReddy02** [comment]
This can be closed as docs have been updated! :)
